/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espoch.sistemagestiontarea.vista;

import ec.edu.espoch.sistemagestiontarea.controlador.Controlador;

/**
 *
 * @author papel
 */
public class Completas extends javax.swing.JFrame {

    private Controlador controlador;

    /**
     * Creates new form Completas
     */
    public Completas() {
        initComponents();
    }

    
    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    public Completas(Interfaz interfaz, Pendientes vistaPendientes) {
        controlador = new Controlador(this, vistaPendientes, interfaz);
        interfaz.setControlador(controlador);
        vistaPendientes.setControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbdTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnMostrar = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        MenuTareas1 = new javax.swing.JMenu();
        mItemNueva1 = new javax.swing.JMenuItem();
        mIPendientes1 = new javax.swing.JMenuItem();
        mICompletas1 = new javax.swing.JMenuItem();
        MenuSalir1 = new javax.swing.JMenu();
        menuItemCerrar1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbdTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbdTitulo.setText("TAREAS COMPLETAS");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        MenuTareas1.setText("Tarea");

        mItemNueva1.setText("Nueva");
        mItemNueva1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemNueva1ActionPerformed(evt);
            }
        });
        MenuTareas1.add(mItemNueva1);

        mIPendientes1.setText("Pendientes");
        mIPendientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mIPendientes1ActionPerformed(evt);
            }
        });
        MenuTareas1.add(mIPendientes1);

        mICompletas1.setText("Completas");
        mICompletas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mICompletas1ActionPerformed(evt);
            }
        });
        MenuTareas1.add(mICompletas1);

        jMenuBar2.add(MenuTareas1);

        MenuSalir1.setText("Salir");
        MenuSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalir1ActionPerformed(evt);
            }
        });

        menuItemCerrar1.setText("Cerrar");
        menuItemCerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCerrar1ActionPerformed(evt);
            }
        });
        MenuSalir1.add(menuItemCerrar1);

        jMenuBar2.add(MenuSalir1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(lbdTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(btnMostrar)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbdTitulo)
                .addGap(18, 18, 18)
                .addComponent(btnMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mItemNueva1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemNueva1ActionPerformed
        // TODO add your handling code here:
        Interfaz obInterfaz = new Interfaz();
        obInterfaz.setVisible(true);
        obInterfaz.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_mItemNueva1ActionPerformed

    private void menuItemCerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCerrar1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_menuItemCerrar1ActionPerformed

    private void MenuSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuSalir1ActionPerformed

    private void mIPendientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mIPendientes1ActionPerformed
        // TODO add your handling code here:
        Pendientes objPendientes = new Pendientes();
        objPendientes.setVisible(true);
        objPendientes.setLocationRelativeTo(null);
        controlador.tareasPendiente();
        this.dispose();


    }//GEN-LAST:event_mIPendientes1ActionPerformed

    private void mICompletas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mICompletas1ActionPerformed
        // TODO add your handling code here:
        Completas objCompletas = new Completas();
        objCompletas.setVisible(true);
        objCompletas.setLocationRelativeTo(null);
        controlador.tareasCompletadas();
        this.dispose();


    }//GEN-LAST:event_mICompletas1ActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        if (controlador == null) {
            controlador.tareasCompletadas();
        } else {
            System.out.println("Error: controlador no inicializado.");
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    public void setMostarTareas(String[] datos) {
        String cadena = "";
        for (int i = 0; i < datos.length; i++) {
            cadena = cadena + datos[i];
        }
        jTextArea1.setText(cadena);
    }

    public void error(String error) {
        if (jTextArea1 != null) {
        jTextArea1.setText(error);
    } else {
        System.err.println("jTextArea1 no está inicializado.");
    }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuSalir1;
    private javax.swing.JMenu MenuTareas1;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbdTitulo;
    private javax.swing.JMenuItem mICompletas1;
    private javax.swing.JMenuItem mIPendientes1;
    private javax.swing.JMenuItem mItemNueva1;
    private javax.swing.JMenuItem menuItemCerrar1;
    // End of variables declaration//GEN-END:variables

}
