/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espoch.sistemagestiontarea.vista;

import ec.edu.espoch.sistemagestiontarea.controlador.Controlador;
import ec.edu.espoch.sistemagestiontarea.modelo.GestorTareas;
<<<<<<< HEAD
import ec.edu.espoch.sistemagestiontarea.modelo.Tarea;

=======
import java.util.List;
>>>>>>> 502f3f6d6b802e38f48612159d84196023abb081

/**
 *
 * @author SO-LAB1-PC20
 */
public class Interfaz extends javax.swing.JFrame {

    private Controlador controlador;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        GestorTareas gestorTareas = new GestorTareas();
        Completas vistaCompletas = new Completas();
        Pendientes vistaPendientes = new Pendientes();
        controlador=new Controlador(vistaCompletas, vistaPendientes, this);
        
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupCompletaSiNo = new javax.swing.ButtonGroup();
        TextDescripcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbdTitulo = new javax.swing.JLabel();
        lbdTituloTarea = new javax.swing.JLabel();
        lbdDescripcion = new javax.swing.JLabel();
        TextTituloTarea = new javax.swing.JTextField();
        RdbTareaSI = new javax.swing.JRadioButton();
        RdbTareaNo = new javax.swing.JRadioButton();
        BtnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        BtnAgregar = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        MenuTareas = new javax.swing.JMenu();
        mItemNueva = new javax.swing.JMenuItem();
        mIPendientes = new javax.swing.JMenuItem();
        mICompletas = new javax.swing.JMenuItem();
        MenuSalir = new javax.swing.JMenu();
        menuItemCerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbdTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbdTitulo.setText("Gestión de Tareas");

        lbdTituloTarea.setText("Título:");

        lbdDescripcion.setText("Descripción:");

        TextTituloTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTituloTareaActionPerformed(evt);
            }
        });

        btnGroupCompletaSiNo.add(RdbTareaSI);
        RdbTareaSI.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RdbTareaSI.setText("Completa");

        btnGroupCompletaSiNo.add(RdbTareaNo);
        RdbTareaNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RdbTareaNo.setText("Pendiente");

        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        BtnAgregar.setText("Agregar");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        MenuTareas.setText("Tarea");

        mItemNueva.setText("Nueva");
        mItemNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemNuevaActionPerformed(evt);
            }
        });
        MenuTareas.add(mItemNueva);

        mIPendientes.setText("Pendientes");
        mIPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mIPendientesActionPerformed(evt);
            }
        });
        MenuTareas.add(mIPendientes);

        mICompletas.setText("Completas");
        mICompletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mICompletasActionPerformed(evt);
            }
        });
        MenuTareas.add(mICompletas);

        MenuBar.add(MenuTareas);

        MenuSalir.setText("Salir");
        MenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalirActionPerformed(evt);
            }
        });

        menuItemCerrar.setText("Cerrar");
        menuItemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCerrarActionPerformed(evt);
            }
        });
        MenuSalir.add(menuItemCerrar);

        MenuBar.add(MenuSalir);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbdDescripcion)
                            .addComponent(jLabel1))
                        .addGap(304, 304, 304))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RdbTareaNo)
                            .addComponent(lbdTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnAgregar)
                                .addGap(138, 138, 138)
                                .addComponent(BtnLimpiar))
                            .addComponent(jScrollPane1))
                        .addGap(111, 111, 111))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(lbdTituloTarea)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextTituloTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(RdbTareaSI)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbdTitulo)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextTituloTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbdTituloTarea))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbdDescripcion)
                    .addComponent(TextDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RdbTareaSI)
                    .addComponent(RdbTareaNo))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLimpiar)
                    .addComponent(BtnAgregar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextTituloTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTituloTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTituloTareaActionPerformed

    private void mItemNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemNuevaActionPerformed
        // TODO add your handling code here:
        Interfaz obInterfaz = new Interfaz();
        obInterfaz.setVisible(true);
        obInterfaz.setLocationRelativeTo(null);
        this.dispose();

        controlador.procesoGestorTareas();
        limpiarCampos();
    }//GEN-LAST:event_mItemNuevaActionPerformed

    private void limpiarCampos() {
        TextTituloTarea.setText("");
        TextDescripcion.setText("");
        RdbTareaSI.setSelected(false);
        RdbTareaNo.setSelected(false);
        jTextArea1.setText("");
    }

    private void MenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MenuSalirActionPerformed

    private void menuItemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_menuItemCerrarActionPerformed

    private void mIPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mIPendientesActionPerformed
        // TODO add your handling code here:
        Pendientes objPendientes = new Pendientes();
        objPendientes.setVisible(true);
        objPendientes.setLocationRelativeTo(null);
        this.dispose();
         controlador.procesoGestorTareas();
    }//GEN-LAST:event_mIPendientesActionPerformed

    private void mICompletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mICompletasActionPerformed
        // TODO add your handling code here:
        Completas objCompletas = new Completas();
        objCompletas.setVisible(true);
        objCompletas.setLocationRelativeTo(null);
        this.dispose();
        
        controlador.procesoGestorTareas();
    }//GEN-LAST:event_mICompletasActionPerformed

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        // TODO add your handling code here:
        controlador.procesoGestorTareas();
        

    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    public String getTituloTarea() {
        return TextTituloTarea.getText();
    }

    public String getDescripcion() {
        return TextDescripcion.getText();
    }

    public void setMostarTareas(String mostrar) {
        jTextArea1.setText(String.valueOf(mostrar));
    }
    

    
    public boolean setPendiente() {
        return RdbTareaNo.isSelected();
    }
    
    public boolean setCompletada() {
        return RdbTareaSI.isSelected();
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MenuSalir;
    private javax.swing.JMenu MenuTareas;
    private javax.swing.JRadioButton RdbTareaNo;
    private javax.swing.JRadioButton RdbTareaSI;
    private javax.swing.JTextField TextDescripcion;
    private javax.swing.JTextField TextTituloTarea;
    private javax.swing.ButtonGroup btnGroupCompletaSiNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbdDescripcion;
    private javax.swing.JLabel lbdTitulo;
    private javax.swing.JLabel lbdTituloTarea;
    private javax.swing.JMenuItem mICompletas;
    private javax.swing.JMenuItem mIPendientes;
    private javax.swing.JMenuItem mItemNueva;
    private javax.swing.JMenuItem menuItemCerrar;
    // End of variables declaration//GEN-END:variables

    public boolean setPendiente() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
